In [1]:
# import numpy
import numpy as np

In [5]:
# numpy arange

# gives 1d array 
a = np.arange(15)
print(a)

a = np.arange(2,15)
print(a)

a = np.arange(2,15,2)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


In [10]:
# numpy reshape

# converts 1d array to given provided array
# (row * column)
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
a = np.arange(16).reshape(2, 2, 4)
print("array is \n\n {} \n".format(a))

# get shape of an array
print("shape of array is {}".format(a.shape))

# get dimension of an array
print("dimension of array is {}".format(a.ndim))

# get size of elements of an array
print("size of array is {}".format(a.size))

array is 

 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

shape of array is (2, 2, 4)
dimension of array is 3
size of array is 16


## Array Creation

In [28]:
# from python list

my_list = [ [1,3,5,7] , [2,4,6,8] ]
print(type(my_list))

my_np_array = np.array(my_list)
print(type(my_np_array))

# get shape of an array
print("shape of array is {}".format(my_np_array.shape))

# get dimension of an array
print("dimension of array is {}".format(my_np_array.ndim))

# get size of elements of an array
print("size of array is {}".format(my_np_array.size))

<type 'list'>
<type 'numpy.ndarray'>
shape of array is (2, 4)
dimension of array is 2
size of array is 8


In [29]:
# create zeros array
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [30]:
# create ones array
np.ones( (3,4) )

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [32]:
# create random array
np.empty( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## linspace

- get numbers between two points

In [38]:
np.linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [39]:
from numpy import pi
np.linspace( 0, pi, 10 )

array([ 0.        ,  0.34906585,  0.6981317 ,  1.04719755,  1.3962634 ,
        1.74532925,  2.0943951 ,  2.44346095,  2.7925268 ,  3.14159265])

## numpy random

In [40]:
np.random.rand(3,2)

array([[ 0.68543134,  0.05989286],
       [ 0.02276247,  0.87271796],
       [ 0.90003156,  0.768343  ]])

In [41]:
# Return a sample (or samples) from the “standard normal” distribution.
2.5 * np.random.randn(2, 4) + 3

array([[ 4.35627742,  1.10626838,  8.87790999,  1.75241195],
       [ 6.34865532,  2.87090051,  0.32242871,  2.24435301]])

## array creation using function

In [42]:
def my_func(a,b,c):
    return a*a + b*b + c*c

np.from_function(my_func,(3,3,3))

AttributeError: 'module' object has no attribute 'from_function'