In [1]:
# import numpy
import numpy as np

In [5]:
# numpy arange

# gives 1d array 
a = np.arange(15)
print(a)

a = np.arange(2,15)
print(a)

a = np.arange(2,15,2)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


In [10]:
# numpy reshape

# converts 1d array to given provided array
# (row * column)
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
a = np.arange(16).reshape(2, 2, 4)
print("array is \n\n {} \n".format(a))

# get shape of an array
print("shape of array is {}".format(a.shape))

# get dimension of an array
print("dimension of array is {}".format(a.ndim))

# get size of elements of an array
print("size of array is {}".format(a.size))

array is 

 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

shape of array is (2, 2, 4)
dimension of array is 3
size of array is 16
