In [1]:
# import numpy
import numpy as np

In [5]:
# numpy arange

# gives 1d array 
a = np.arange(15)
print(a)

a = np.arange(2,15)
print(a)

a = np.arange(2,15,2)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


In [10]:
# numpy reshape

# converts 1d array to given provided array
# (row * column)
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
a = np.arange(16).reshape(2, 2, 4)
print("array is \n\n {} \n".format(a))

# get shape of an array
print("shape of array is {}".format(a.shape))

# get dimension of an array
print("dimension of array is {}".format(a.ndim))

# get size of elements of an array
print("size of array is {}".format(a.size))

array is 

 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

shape of array is (2, 2, 4)
dimension of array is 3
size of array is 16


## Array Creation

In [28]:
# from python list

my_list = [ [1,3,5,7] , [2,4,6,8] ]
print(type(my_list))

my_np_array = np.array(my_list)
print(type(my_np_array))

# get shape of an array
print("shape of array is {}".format(my_np_array.shape))

# get dimension of an array
print("dimension of array is {}".format(my_np_array.ndim))

# get size of elements of an array
print("size of array is {}".format(my_np_array.size))

<type 'list'>
<type 'numpy.ndarray'>
shape of array is (2, 4)
dimension of array is 2
size of array is 8


In [29]:
# create zeros array
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [30]:
# create ones array
np.ones( (3,4) )

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [32]:
# create random array
np.empty( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## linspace

- get numbers between two points

In [38]:
np.linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [39]:
from numpy import pi
np.linspace( 0, pi, 10 )

array([ 0.        ,  0.34906585,  0.6981317 ,  1.04719755,  1.3962634 ,
        1.74532925,  2.0943951 ,  2.44346095,  2.7925268 ,  3.14159265])

## numpy random

In [40]:
np.random.rand(3,2)

array([[ 0.68543134,  0.05989286],
       [ 0.02276247,  0.87271796],
       [ 0.90003156,  0.768343  ]])

In [41]:
# Return a sample (or samples) from the “standard normal” distribution.
2.5 * np.random.randn(2, 4) + 3

array([[ 4.35627742,  1.10626838,  8.87790999,  1.75241195],
       [ 6.34865532,  2.87090051,  0.32242871,  2.24435301]])

## array creation using function

In [45]:
def my_func(a,b,c):
    return a*a + b*b + c*c

np.fromfunction(my_func,(3,3,3))

array([[[  0.,   1.,   4.],
        [  1.,   2.,   5.],
        [  4.,   5.,   8.]],

       [[  1.,   2.,   5.],
        [  2.,   3.,   6.],
        [  5.,   6.,   9.]],

       [[  4.,   5.,   8.],
        [  5.,   6.,   9.],
        [  8.,   9.,  12.]]])

## Basic Operations

In [53]:
a = np.array( [20,30,40,50] )
b = np.array( [2,3,4,5] )

# addition
c = a + b
print(c)

# sub
c = a - b
print(c)

# mul
c = a * b
print(c)

# div
c = a / b
print(c)

# power
c = a ** b
print(c)

# boolean compare
c = a < b
print(c)

[22 33 44 55]
[18 27 36 45]
[ 40  90 160 250]
[10 10 10 10]
[      400     27000   2560000 312500000]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[False False False False]


In [60]:
a = np.array( [20,30,40,50] )

# sin
c = np.sin(a) * 10
print(c)

# exp
c = np.exp(a) 
print(c)

# sqrt
c = np.sqrt(a) * 10
print(c)

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[  4.85165195e+08   1.06864746e+13   2.35385267e+17   5.18470553e+21]
[ 44.72135955  54.77225575  63.2455532   70.71067812]


## numpy matrix multiplication

In [57]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

# elemetn wise product
print(A*B)

# dot product (matrix multiplicarion)
print(A.dot(B))
print(np.dot(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


## Indexing, Slicing and Iterating

In [64]:
# 1d

a = np.arange(10)**3
print(a)

# acces element at specific index
print(a[2])

# access elements within range
print(a[2:5])

# access elements within range
print(a[2:9:2])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[  8  64 216 512]


In [71]:
# nd

def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)

print(b)

# access specific element
print(b[2,3])

print(b[0:5, 0])

print(b[0:5, 0:2])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 0 10 20 30 40]
[[ 0  1]
 [10 11]
 [20 21]
 [30 31]
 [40 41]]


## Iteration

In [73]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)

# Iterating over multidimensional arrays is done with respect to the first axis:
for row in b:
    print(row)
    
# However, if one wants to perform an operation on each element in the array, 
# one can use the flat attribute which is an iterator over all the elements of the array:
for element in b.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## array reshape

In [77]:
a = np.floor(10*np.random.random((3,4)))
print(a)

# reshape
a = a.reshape(6,2)
print(a)

# transpose
a = a.T
print(a)



[[ 9.  0.  9.  6.]
 [ 9.  6.  4.  9.]
 [ 1.  1.  4.  8.]]
[[ 9.  0.]
 [ 9.  6.]
 [ 9.  6.]
 [ 4.  9.]
 [ 1.  1.]
 [ 4.  8.]]
[[ 9.  9.  9.  4.  1.  4.]
 [ 0.  6.  6.  9.  1.  8.]]
